dev: # this needs to match the profile: in dbt_project.yml
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth           # Run "gcloud auth application-default login" in Terminal
      project: henrytxz       # GCP project id
      dataset: "{{ env_var('YOUR_DBT_DEV_DATASET') }}"
      threads: 4
      location: US

audit:
  target: audit
  outputs:
    audit:
      type: bigquery
      method: service-account
      keyfile: "{{ env_var('PATH_GCP_KEYFILE') }}"
      project: henrytxz
      dataset: data_demo_audit # different from the dev target
      threads: 4
      location: US

prod:
  target: prod
  outputs:
    prod:
      type: bigquery
      method: service-account
      keyfile: "{{ env_var('PATH_GCP_KEYFILE') }}"
      project: henrytxz
      dataset: data_demo_prod # different from the dev target
      threads: 4
      location: US