dev: # this needs to match the profile: in dbt_project.yml
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account # TODO: try OAUTH
      keyfile: "{{ env_var('PATH_GCP_KEYFILE') }}" # The PATH_GCP_KEYFILE env variable needs to be set
      project: henrytxz       # Replace this with your project id
      dataset: data_demo_dev  # The BigQuery concept "dataset" == dbt "schema"
      threads: 4
      location: US

audit:
  target: audit
  outputs:
    audit:
      type: bigquery
      method: service-account
      keyfile: "{{ env_var('PATH_GCP_KEYFILE') }}"
      project: henrytxz
      dataset: data_demo_audit # different from the dev target
      threads: 4
      location: US

prod:
  target: prod
  outputs:
    prod:
      type: bigquery
      method: service-account
      keyfile: "{{ env_var('PATH_GCP_KEYFILE') }}"
      project: henrytxz
      dataset: data_demo_prod # different from the dev target
      threads: 4
      location: US