version: 2

models:
  - name: game_play_activity
    description: "This table records the amount of activity by a player on a given day"

    columns:
      - name: player_id
        tests:
          - not_null

      - name: event_date
        tests:
          - not_null

      - name: device_id

      - name: games_played
